volumes:
  project_web_cars_local_postgres_data: {}


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start.sh
    container_name: project_web_cars_local_django
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.env
    image: project_web_cars_local_django
    ports:
      - '8000:8000'
    volumes:
      - /app/.venv
      - .:/app:z

  postgres:
    container_name: project_web_cars_local_postgres
    env_file:
      - ./.envs/.local/.env
    image: postgres:17
    ports:
    - "5432:5432"
    volumes:
      - project_web_cars_local_postgres_data:/var/lib/postgresql/data
